/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevSkinPreviewRouteImport } from './routes/dev/skin-preview'
import { Route as ApiSkinsImportUrlRouteImport } from './routes/api/skins/import-url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSkinPreviewRoute = DevSkinPreviewRouteImport.update({
  id: '/dev/skin-preview',
  path: '/dev/skin-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinsImportUrlRoute = ApiSkinsImportUrlRouteImport.update({
  id: '/api/skins/import-url',
  path: '/api/skins/import-url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/skin-preview': typeof DevSkinPreviewRoute
  '/api/skins/import-url': typeof ApiSkinsImportUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/skin-preview': typeof DevSkinPreviewRoute
  '/api/skins/import-url': typeof ApiSkinsImportUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/skin-preview': typeof DevSkinPreviewRoute
  '/api/skins/import-url': typeof ApiSkinsImportUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/skin-preview' | '/api/skins/import-url'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/skin-preview' | '/api/skins/import-url'
  id: '__root__' | '/' | '/dev/skin-preview' | '/api/skins/import-url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevSkinPreviewRoute: typeof DevSkinPreviewRoute
  ApiSkinsImportUrlRoute: typeof ApiSkinsImportUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/skin-preview': {
      id: '/dev/skin-preview'
      path: '/dev/skin-preview'
      fullPath: '/dev/skin-preview'
      preLoaderRoute: typeof DevSkinPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skins/import-url': {
      id: '/api/skins/import-url'
      path: '/api/skins/import-url'
      fullPath: '/api/skins/import-url'
      preLoaderRoute: typeof ApiSkinsImportUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevSkinPreviewRoute: DevSkinPreviewRoute,
  ApiSkinsImportUrlRoute: ApiSkinsImportUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
